### ISSUE TITLE
Shifts from taguspark not showing

### ISSUE THREAD

**Issue by tiagoteixeira03** [Criador-Horarios/Criador-Horarios#94]
To reproduce the error, follow these steps:

- Select MEIC-T.
- Select the course "Língua Natural."
- In the available shifts table, only shifts in Alameda will appear.

The same issue also occurs with the courses "Análise e Integração de Dados" and "Aprendizagem Profunda."

A similar issue was happening with another website used to generate schedules, which was resolved in [this commit](https://github.com/joanasesinando/gerador-horarios-ist/commit/97f69971f6e4272f10086c4ac3ea45a3e1edb625).

**Comment by masterzeus05** [comment]
Looks like the same issue as: https://github.com/Criador-Horarios/Criador-Horarios/issues/93
