### ISSUE TITLE
Classes time is in user device's timezone

### ISSUE THREAD

**Issue by tomas7770** [Criador-Horarios/Criador-Horarios#95]
The time of classes in the schedule is in the user device's configured timezone; e.g if a class is at 10:00 WEST (Lisbon) and the device's timezone is set to AZOT (Azores), it shows up as 9:00.

This doesn't make sense because most (if not all) classes are in person, and therefore the campus location's timezone is most relevant.

In addition, the schedule limits are always 8:00 and 20:00, causing some classes to partly/totally disappear due to this discrepancy.

**Comment by masterzeus05** [comment]
Should be fixed by https://github.com/Criador-Horarios/Criador-Horarios/pull/96
